### ISSUE TITLE
freeing synths

### ISSUE THREAD

**Issue by demacdo** [enrike/sc#6]
Hi, I'm having an issue freeing synths. When I run, for example, the _groups.py_ script, everything runs fine until trying to free the synths. This has persisted among all my implementations. 

From _groups.py_, this is the resulting output:
```
loading bufnum with ID 0
pan 0.00949658643344 amp 0.55447710064
pan 0.625167511009 amp 0.200161115288
pan 0.635937703659 amp 0.963568677795
pan 0.546788197736 amp 0.833285079886
pan -0.711556051208 amp 0.84069871534
Traceback (most recent call last):
  File "groups.py", line 48, in <module>
    for p in playerlist : p.free() ## free all
  File "/Library/Python/2.7/site-packages/sc/sc.py", line 193, in free
    if self.position :
AttributeError: 'Synth' object has no attribute 'position'
```

Thanks!

**Comment by enrike** [comment]
Hi, I think that something is wrong because the ID of the bufnum is 0. I think it means it did not load the sample file properly. Are you sure it is located under "sounds" and that you are writing the right name?
compare your output with mine

created new group with ID  1001
1002 < created node id
1003 < created node id
1004 < created node id
loading bufnum with ID 0
pan -0.727849555759 amp 0.146634522434
pan 0.716578369244 amp 0.51087022231
pan 0.38093343928 amp 0.492840607378
pan 0.29188844422 amp 0.701092470689
pan -0.825433746461 amp 0.635067348861
quiting

**Comment by demacdo** [comment]
Hey, thanks for getting back to me. I just confirmed that the sample (numeros.wav, in the sound folder) appears to be loading properly, though the buffer number is still 0. (Removing the sample file results in a “File XXX does NOT exist” in the terminal.

**Comment by enrike** [comment]
hi again, sorry I was confused before, bufnum is ok being 0 ID

This you are getting is weird. are you sure you are running the latest version of the code? check the source code here
https://github.com/enrike/sc/blob/master/sc/sc.py
In the current version in line 193 there is no "if self.position :". That line of code is in 198 and it is commented out, both 198 and 199 are commented. It looks like that part of the code gave some errors long time ago and I removed it. Try to get the latest code or comment out those lines.
